[package]
name = "i3-scratchmenu"
version = "0.1.0"
authors = ["aedoq <aedoq@protonmail.com>"]
edition = "2018"

[dependencies]
"serde" = { version = "1.0", features = ["derive"] }
"serde_json" = "1.0"
